# Generated by Django 5.0.2 on 2024-02-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_city_account_first_name_account_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
