# Generated by Django 5.0.2 on 2024-02-21 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Package',
            new_name='package',
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
            preserve_default=False,
        ),
    ]
