# Generated by Django 5.0.2 on 2024-02-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_package_variation_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('timeslot', models.IntegerField(blank=True, choices=[(0, '9-10'), (0, '10-11'), (0, '11-12'), (0, '12-1'), (0, '2-3'), (0, '3-4'), (0, '4-5')], null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
