# Generated by Django 5.0.2 on 2024-02-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_slot_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='timeslot',
            field=models.IntegerField(blank=True, choices=[(0, '9-10'), (1, '10-11'), (2, '11-12'), (3, '12-1'), (4, '2-3'), (5, '3-4'), (6, '4-5')], null=True),
        ),
    ]
